### ISSUE TITLE
get Date From Norwegian Personal Identification Number - For those born after 1999

### ISSUE THREAD

**Issue by brada1703** [InductiveComputerScience/fodselsnummer#1]
Hi Martin,

First of all, thank you very much for publishing this data. It has been very helpful!

I have a question regarding getting the birthdates of people born after 1999. On this [page](https://repo.progsbase.com/repoviewer/no.inductive.libraries/foedselsnummer/0.1.2///getDateFromNorwegianPersonalIdentificationNumber/), it is mentioned that we can use a combination of the individnummer and the birthdate (DDMMYY) to understand the century. However, it is limited to 1800 and 1900. For those born in 2000 or later, how should we handle these cases?

Thank you so much,
Brad

**Comment by brada1703** [comment]
@martinfjohansen , I think I found a solution (and submitted a pull request to fix the JS at least). Let me know what you think. https://github.com/InductiveComputerScience/fodselsnummer/pull/2

Thanks!

**Comment by martinfjohansen** [comment]
Thanks, you are indeed correct that we had a bug in this library. Your fix was also correct, but we had a number of new fixes to add as well.

Thanks a lot, and check out our bug-bounty program where we hand out rewards for people who find bugs in out libraries:

https://www.progsbase.com/bug-bounty/

**Comment by brada1703** [comment]
Hey that's great! Thanks Martin 🙌
